environment: production
domain: null

bun:
  image: qwik-aesthetic
  port: 3000
  tag: auth
  env:
    WEBHOOK: null
    API_TOKEN: null
    SUPABASE_URL: null
    SUPABASE_KEY: null

n8n:
  image: docker.n8n.io/n8nio/n8n
  tag: latest
  replicas: 1
  env:
    N8N_PORT: 5678
    N8N_ENCRYPTION_KEY: null
    NODE_ENV: "production"
    GENERIC_TIMEZONE: null
    N8N_DIAGNOSTICS_ENABLED: false
    N8N_VERSION_NOTIFICATIONS_ENABLED: false
    N8N_TEMPLATES_ENABLED: false
    N8N_LOG_LEVEL: debug
    QUEUE_HEALTH_CHECK_ACTIVE: "true"
  initFiles:
    enabled: true
    credsPath: "n8n_files/creds_all.json"
    workflowsPath: "n8n_files/workflow.json"
