services:
  bun:
    build: .
    container_name: bun
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - API_TOKEN=${API_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - mynetwork
    restart: unless-stopped
    command: ["bun", "run", "serve"]

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    environment:
      - N8N_PROTOCOL=${N8N_PROTO}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - WEBHOOK_URL=https://${N8N_HOST}.${DOMAIN_NAME}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Brussels
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_files:/home/node/files # Local files mapping (optional)
    networks:
      - mynetwork
    entrypoint: >
      sh -c "
        n8n start
      "

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
    volumes:
      - caddy_data:/data
      - ./caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - mynetwork
    restart: unless-stopped

networks:
  mynetwork:
    driver: bridge

volumes:
  caddy_data:
    external: true
  n8n_data:
    external: true
