apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-n8n
  labels:
    app: {{ .Release.Name }}-n8n
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.n8n.replicas }}  
  selector:
    matchLabels:
      app: {{ .Release.Name }}-n8n
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-n8n
    spec:
      initContainers:
        - name: init-config
          image: alpine
          command:
            - sh
            - "-c"
            - |
              echo '{"encryptionKey": "'$N8N_ENCRYPTION_KEY'"}' > /data/config && \
              chown 1000:1000 /data/config && \
              chmod 600 /data/config
          env:
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: N8N_ENCRYPTION_KEY
          volumeMounts:
            - name: {{ .Release.Name }}-n8n-data
              mountPath: /data

      containers:
        - name: n8n
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: "{{ .Values.n8n.image }}:{{ .Values.n8n.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-n8n-envconfig
          env:
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: N8N_ENCRYPTION_KEY
          volumeMounts:
            - name: {{ .Release.Name }}-n8n-data
              mountPath: /home/node/.n8n
            - name: {{ .Release.Name }}-n8n-files
              mountPath: /home/node/files
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: {{ .Values.n8n.env.N8N_PORT | int }}
              name: n8n
          lifecycle:
            postStart:
              exec:
                command:
                    - "/bin/sh"
                    - "-c"
                    - |
                      set -e
                      n8n import:credentials --input=/home/node/files/creds.json
                      n8n import:workflow --input=/home/node/files/workflows.json
                      n8n update:workflow --id=PgnuLOJDGJgX1OeB --active=false
                      n8n update:workflow --id=PgnuLOJDGJgX1OeB --active=true
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.n8n.env.N8N_PORT | int }}
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 3
      volumes:
        - name: {{ .Release.Name }}-n8n-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-n8n-pvc
        - name: {{ .Release.Name }}-n8n-files
          configMap:
            name: {{ .Release.Name }}-n8n-files
