apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-n8n-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hcloud-volumes
  csi:
   # hetzner-csi-driver
    driver: csi.hetzner.cloud
    volumeHandle: {{ .Values.volume_id }}  # Replace this with your existing volume ID
