apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`n8n.{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-n8n-svc
          port: {{ .Values.n8n.env.N8N_PORT }}
    - match: Host(`{{ .Values.domain }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-bun-svc
          port: 80
  tls:
    certResolver: letsencrypt
