apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer-staging
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.email }}
    # We use the staging server here for testing to avoid hitting production
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: "tls-{{ .Release.Name }}-ingress-http"
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-issuer-production
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    email: {{ .Values.email }}
    # We use the production server here for actual deployments
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # if not existing, it will register a new account and stores it
      name: "tls-{{ .Release.Name }}-ingress-http"
    solvers:
      - http01:
          # The ingressClass used to create the necessary ingress routes
          ingress:
            class: traefik

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/issuer: "{{ .Release.Name }}-issuer-{{ .Values.environment }}"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .Values.domain }}
        - "n8n.{{ .Values.domain }}"
      secretName: "tls-{{ .Release.Name }}-ingress-http"
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-bun-svc
                port:
                  number: 80
    - host: "n8n.{{ .Values.domain }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-n8n-svc
                port:
                  number: {{ .Values.n8n.env.N8N_PORT }}
