apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
spec:
  ingressClassName: traefik  # Use the new field to specify the Ingress class
  tls:
    - hosts:
        - "n8n.{{ .Values.domain }}"
        - {{ .Values.domain }}
      secretName: {{.Release.Name}}-secret-tls  # Ensure you have a TLS secret
  rules:
    - host: "n8n.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-n8n-svc
                port:
                  number: {{ .Values.n8n.env.N8N_PORT }}

    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-bun-svc
                port:
                  number: 80
