apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-n8n-envconfig
data:
  N8N_HOST: "{{ .Release.Name }}-n8n-svc.{{ .Release.Namespace }}.svc.cluster.local"
  N8N_PORT: "{{ .Values.n8n.env.N8N_PORT }}"
  NODE_ENV: "{{ .Values.n8n.env.NODE_ENV }}"
  N8N_DIAGNOSTICS_ENABLED: "{{ .Values.n8n.env.N8N_DIAGNOSTICS_ENABLED }}"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "{{ .Values.n8n.env.N8N_VERSION_NOTIFICATIONS_ENABLED }}"
  N8N_TEMPLATES_ENABLED: "{{ .Values.n8n.env.N8N_TEMPLATES_ENABLED }}"
  GENERIC_TIMEZONE: "{{ .Values.n8n.env.GENERIC_TIMEZONE }}"
  DOMAIN_NAME: "{{ .Values.domain }}"
  WEBHOOK_URL: "{{ .Values.n8n.env.WEBHOOK_URL }}"
  N8N_LOG_LEVEL: "{{ .Values.n8n.env.N8N_LOG_LEVEL }}"
  QUEUE_HEALTH_CHECK_ACTIVE: "{{ .Values.n8n.env.QUEUE_HEALTH_CHECK_ACTIVE }}"
