apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.env.N8N_ENCRYPTION_KEY | b64enc | quote }}
  SUPABASE_KEY: {{ .Values.bun.env.SUPABASE_KEY | b64enc | quote }}
  SUPABASE_URL: {{ .Values.bun.env.SUPABASE_URL | b64enc | quote }}
  API_TOKEN: {{ .Values.bun.env.API_TOKEN | b64enc | quote }}
