---
- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes

- name: Add user to microk8s group
  user:
    name: "{{ ansible_user }}"
    groups: microk8s
    append: yes

- name: Enable DNS
  command: microk8s enable dns

- name: Enable hostpath-storage
  command: microk8s enable hostpath-storage

- name: Enable metrics
  command: microk8s enable metrics-server

- name: Enable dashboard
  command: microk8s enable dashboard

- name: Enable community
  command: microk8s enable community

- name: Enable metallb
  command: microk8s enable metallb:"{{ lb_ip_pool }}"


- name: Ensure local Kubeconfig directory exists
  local_action:
    module: file
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: '0700'
  become: no  # Prevent root escalation

- name: Get Kubeconfig from MicroK8s
  command: microk8s config
  register: microk8s_config

- name: Save Kubeconfig locally (overwrite if exists)
  local_action:
    module: copy
    content: "{{ microk8s_config.stdout }}"
    dest: "{{ lookup('env', 'HOME') }}/.kube/microk8s-config"
    mode: '0600'  # Set to read/write for the local user
    force: yes  # Ensures the file is overwritten if it already exists
  become: no

- name: Add Traefik Helm Repo
  command:
    cmd: microk8s helm repo add traefik https://traefik.github.io/charts
  ignore_errors: true

- name: Update Helm Repos
  command:
    cmd: microk8s helm repo update


# Apply a PersistentVolumeClaim for Traefik's ACME storage
- name: Apply PersistentVolumeClaim for ACME Storage
  template:
    src: templates/traefik-pvc.yaml.j2
    dest: /tmp/traefik-pvc.yaml

- name: Deploy PVC for Traefik ACME
  command:
    cmd: microk8s kubectl apply -f /tmp/traefik-pvc.yaml

# Install Traefik with Let's Encrypt support using Helm
- name: Install Traefik with Let's Encrypt support
  command: >
    microk8s helm upgrade -i traefik traefik/traefik --namespace kube-system
    --set certificatesResolvers.letsencrypt.acme.email={{ lookup('env', 'EMAIL') }}
    --set certificatesResolvers.letsencrypt.acme.storage="/data/acme.json"
    --set certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web
    --set entryPoints.web.address=:80
    --set entryPoints.websecure.address=:443
    --set persistence.enabled=true
    --set persistence.existingClaim="traefik-acme-pvc"
    --set persistence.storageClassName="microk8s-hostpath"


- name: Traefik CRDs
  command:
    cmd: microk8s kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.3/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
